### ISSUE TITLE
sel.baseNode is  null 

### ISSUE THREAD

**Issue by goldwizard13** [antoniandre/richer-than-rich#4]
src/documentation/index.vue
 let nearestBlockEl = utils.getNearestBlockNode(sel.baseNode, sel.baseOffset, inputField.value)
sel.baseNode null 

 there were debates on naming:

    baseNode is alias for anchorNode
    extentNode for focusNode

Also, baseOffset is still not in the official specs, better use anchorOffset which I think does approximately the same thing (but is supported in all browsers).

**Comment by antoniandre** [comment]
Hi @goldwizard13 thanks for pointing that out. After doing my own digging, it seems that you're right. Even if baseNode and extentNode are more modern, they haven't been added to the W3C specs because the've been aliases.
I've updated the code accordingly in 0.4.3

Ref: https://stackoverflow.com/a/78938214/2012407
